### ISSUE TITLE
[docs] Add alt text on images

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#4028]
## Summary

For every image in LightGBM's documentation, alternative text that describes the image should be added.

## Motivation

People with limited vision use screen readers to view web pages. When these screen readers encounter an image, they will only read some placeholder like "IMAGE" by default. However, if [the "alt" tag](https://www.w3schools.com/tags/att_img_alt.asp) is specified, many screen readers will use that instead.

Adding alt text for images would improve the accessibility of LightGBM's documentation for users who use screen readers.

## Description

To help with this issue, submit a pull request that adds alt text for images in LightGBM's documentation. Please limit pull requests to only 1 file, to simplify reviews.

As of this writing, the following documentation files have images (based on `git grep -E "\.\. image" docs`)

* [x] `docs/Features.rst` (#4036)
* [x] `docs/GPU-Performance.rst` (#4036)
* [x] `docs/GPU-Windows.rst` (#4036)
* [x] `docs/Parallel-Learning-Guide.rst` (#4030)
* [x] `docs/Parameters-Tuning.rst` (#4035)
* [x] `docs/gcc-Tips.rst` (#4187)
* [x] `docs/index.rst` (#4029)

When adding alt text, follow the advice in https://accessibility.psu.edu/images/alttext/.

> ...include what you might relay over the phone

> it should describe the image. It should NOT include information about copyright or any extra information that would be relevant to a seeing audience.

This can be done with the `:alt:` parameter in Sphinx `..image` directives (see [the Sphinx docs](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/images.html) for details).

For example:

```rst
.. image:: ./_static/images/some-image.png
  :alt: A screenshot with build logs from GCC.
```

## References

While working on this, you might also consider some of the recommendations from https://webaim.org/techniques/screenreader/#how. For example, things that should be read out loud as acronyms, like `gcc`, should be spelled out all in capital letters ("GCC").

**Comment by akshitadixit** [comment]
Hello, may I please work on this?

**Comment by jameslamb** [comment]
Sure, thanks @akshitadixit ! Please feel free to submit a pull request based on the description above. Let me know if you have any questions!

**Comment by subhamagrawal7** [comment]
I would like to try and add alt text to Parameters-Tuning.rst. Could you assign this?

**Comment by jameslamb** [comment]
Thanks @subhamagrawal7 ! Please feel free to submit a pull request based on the description above, and let me know if you have any questions.

**Comment by akshitadixit** [comment]
Kindly assign the issue to me.

**Comment by jameslamb** [comment]
sure, thanks!
