### ISSUE TITLE
Migrate to f-strings for the Python code

### ISSUE THREAD

**Issue by StrikerRUS** [microsoft/LightGBM#4136]
Migrate all Python code from old-fashioned `format()` functions, formatting `%` operators and simple concatenations (`+`) to modern [`f-strings`](https://www.python.org/dev/peps/pep-0498/) ([brief guide](https://realpython.com/python-f-strings/)). They are known to be the fastest approach and also increase code readability.

![image](https://user-images.githubusercontent.com/25141164/112898582-aed66d00-90e9-11eb-8cdb-0bc67e69a643.png)
Source: https://cito.github.io/blog/f-strings/.

They are supported starting from Python 3.6 which is the oldest Python version LightGBM officially supports:
https://github.com/microsoft/LightGBM/blob/9cab93a9f3c0b46301a2cd11631223f4ab1daf16/python-package/setup.py#L374-L378

If you're interested in contributing, you do not need to fix all files at once. Pull requests that address all replacements in **one file** are mostly welcomed!

Refer to #4137 for the example PR.

- [x] ``.\.ci\get_workflow_status.py`` (https://github.com/microsoft/LightGBM/pull/4436/files#r663508231)
- [x] ``.\.nuget\create_nuget.py`` (#4162)
- [x] ``.\docs\conf.py`` (#4147)
- [x] ``.\examples\python-guide\advanced_example.py`` (#4386)
- [x] ``.\examples\python-guide\logistic_regression.py`` (#4356)
- [x] ``.\examples\python-guide\plot_example.py`` (#4421)
- [x] ``.\examples\python-guide\simple_example.py`` (#4396)
- [x] ``.\examples\python-guide\sklearn_example.py`` (#4396)
- [x] ``.\examples\python-guide\dask\binary-classification.py``
- [x] ``.\examples\python-guide\dask\multiclass-classification.py``
- [x] ``.\examples\python-guide\dask\prediction.py``
- [x] ``.\examples\python-guide\dask\ranking.py``
- [x] ``.\examples\python-guide\dask\regression.py``
- [x] ``.\helpers\check_dynamic_dependencies.py``
- [x] ``.\helpers\parameter_generator.py`` (#4146)
- [x] ``.\python-package\setup.py`` (#4145)
- [x] ``.\python-package\lightgbm\basic.py`` (#4143)
- [x] ``.\python-package\lightgbm\callback.py`` (#4142)
- [x] ``.\python-package\lightgbm\compat.py``
- [x] ``.\python-package\lightgbm\dask.py`` (#4144)
- [x] ``.\python-package\lightgbm\engine.py`` (#4258)
- [x] ``.\python-package\lightgbm\libpath.py`` (#4137)
- [x] ``.\python-package\lightgbm\plotting.py`` (#4279)
- [x] ``.\python-package\lightgbm\sklearn.py`` (#4188)
- [x] ``.\python-package\lightgbm\__init__.py``
- [x] ``.\tests\cpp_test\test.py``
- [x] ``.\tests\c_api_test\test_.py`` (#4287)
- [x] ``.\tests\python_package_test\test_basic.py`` (#4312)
- [x] ``.\tests\python_package_test\test_consistency.py`` (#4348)
- [x] ``.\tests\python_package_test\test_dask.py`` (#4358)
- [x] ``.\tests\python_package_test\test_dual.py``
- [ ] ``.\tests\python_package_test\test_engine.py`` (#4436)
- [x] ``.\tests\python_package_test\test_plotting.py`` (#4359)
- [x] ``.\tests\python_package_test\test_sklearn.py``
- [x] ``.\tests\python_package_test\test_utilities.py``
- [x] ``.\tests\python_package_test\utils.py``
- [x] ``.\tests\python_package_test\__init__.py``

**Comment by coldkillerr** [comment]
I can work on this if no one is assigned

**Comment by NovusEdge** [comment]
I would like to take this one up if no one's assigned.

**Comment by StrikerRUS** [comment]
@coldkillerr @NovusEdge Thanks! Sure, please feel free to pick up any file(s) you like!

**Comment by akshitadixit** [comment]
Hi may I please work on this?

**Comment by jameslamb** [comment]
@akshitadixit yes please! We'd be grateful for the help.

Please only submit pull requests for a single file, and please check the list of open pull requests at https://github.com/microsoft/LightGBM/pulls since there are a few related to this issue already open.

**Comment by jameslamb** [comment]
Oh also, the code in `python-package` is higher priority than the tests or examples.

**Comment by akshitadixit** [comment]
Sure, I will keep all of this in mind.

**Comment by jameslamb** [comment]
Sure, thank you! Please only submit a pull request for one file at a time. `@` me if you have any questions.

**Comment by akshitadixit** [comment]
Hey, please add a checkmark on the following files since they have no strings that need to be migrated:
* .\python-package\lightgbm\compat.py
* .\tests\python_package_test\__init__.py
* .\tests\python_package_test\utils.py

**Comment by jameslamb** [comment]
ah yes you're right, thanks very much @akshitadixit !

**Comment by sayantan1410** [comment]
Hey, I have a made pull request where I have changed the old syntax of string formatting in the print statements with the new one. 
Kindly check it out and let me know if it can be merged or I have messed up somewhere. The file that I have changed is : 
.\tests\c_api_test\test_.py

Also there are no strings in the file : .\tests\cpp_test\test.py, so no formatting is required for it as well, you can tick them off. 
@jameslamb

**Comment by jameslamb** [comment]
> Also there are no strings in the file : .\tests\cpp_test\test.py, so no formatting is required for it as well, you can tick them off.

excellent, thanks!

**Comment by sayantan1410** [comment]
Hello, can I solve the same issue in some other files as well ? like 
file : .\tests\python_package_test\test_basic.py
@jameslamb

**Comment by jameslamb** [comment]
yes please, as many as you want! Please just be sure to only do one file per pull request.

**Comment by sayantan1410** [comment]
Thank you so much and I will keep that in mind.

**Comment by sayantan1410** [comment]
Hey I want to work on this file: .\tests\python_package_test\test_consistency.py
May I ? 
@jameslamb

**Comment by jameslamb** [comment]
Yes please! You can work on any file listed in the description of this issue.

**Comment by sayantan1410** [comment]
Hey, there's nothing to update in the file : .\tests\python_package_test\test_consistency.py . 
So updating the file: .\tests\python_package_test\test_dask.py

**Comment by jameslamb** [comment]
> Hey, there's nothing to update in the file : .\tests\python_package_test\test_consistency.py .
> So updating the file: .\tests\python_package_test\test_dask.py

I see two places in `test_consistency` that could be updated. Could you please update 

https://github.com/microsoft/LightGBM/blob/20e633875f3c843e25f3877071c950e673b879b6/tests/python_package_test/test_consistency.py#L35

and

https://github.com/microsoft/LightGBM/blob/20e633875f3c843e25f3877071c950e673b879b6/tests/python_package_test/test_consistency.py#L64

to `f"{self.prefix}{suffix}"?

And then we'd greatly appreciate if you do `test_dask.py` (in a separate pull request)

**Comment by sayantan1410** [comment]
Sure, I will update consistency.py then. 
Thank you for correcting me out.

**Comment by sagnik1511** [comment]
Hello, can I contribute to this issue ?? 
 I want to update   **.\examples\python-guide\logistic_regression.py** this file.

**Comment by jameslamb** [comment]
Yes please! Thanks for the help @sagnik1511

**Comment by sagnik1511** [comment]
Thanks, @jameslamb for letting me collaborate !
Do check the [PR](https://github.com/microsoft/LightGBM/pull/4355).
Thank You :)

**Comment by sayantan1410** [comment]
Hey, May I work on this file ?
@jameslamb

**Comment by jameslamb** [comment]
@sayantan1410 thanks for all your help! You can work on any file mentioned in this issue.

**Comment by sayantan1410** [comment]
Thank you !!
@jameslamb

**Comment by amanjha8100** [comment]
Hey, can I contribute to this issue?

**Comment by jameslamb** [comment]
Yes please, we'd be grateful for the help.

**Comment by amanjha8100** [comment]
Thanks, @jameslamb for letting me contribute !
Do check the [PR](https://github.com/microsoft/LightGBM/pull/4421).
Thank You :)

**Comment by amanjha8100** [comment]
Hey @jameslamb is there any other file that needs changing, I am unable to find any?

**Comment by jameslamb** [comment]
> Hey @jameslamb is there any other file that needs changing, I am unable to find any

Thanks for looking! I agree that `helpers/check_dynamic_dependencies.py` doesn't have any strings that need to be changed.

I updated the list in this issue's description:

* `libpath.py` - updated in #4137
* `helpers/check_dynamic_dependencies.py` - I don't see any string concatenation that needs to be updated
* `tests/python_package_test/test_sklearn.py` - I don't see any string concatenation that needs to be updated

`test_engine.py` does have some places that need to be updated but those cases are somewhat complicated so I am going to take that one to close this issue.

Thanks so much for your help! We hope you'll contribute again in the future.

**Comment by amanjha8100** [comment]
Great, it was fun contributing!
