### ISSUE TITLE
[Draft] Oct~Nov iteration Plan

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/LightGBM#4677]
We'd like to experience the practices to use issues tracking recent planned items. This issue is to cover recent updates and changes in the current & coming months, all are welcomed to comments/add in the items you'd like to merge into the iteration. Items by area:

## PRs to be finished in this iteration
- [ ] **P0** - #3234 @shiyu1994 
- [ ] **P0** - #4630 @shiyu1994
- [ ] **P1** - #4266

## Feature requests decomposed from the above PRs
- [ ] **P0** - #4779
- [ ] **P1** - #4780 @hzy46 [break down items](https://github.com/microsoft/LightGBM/issues/4780#issuecomment-968590961)
- [ ] **P1** - #4781
- [ ] **P1** - #4785

## Bug fixes and small improvement
- [x] ignore_column does not work when loading a dataset from a binary file #4657
- [ ] Memory leaks / is better memory management possible? #4239
- [x] Using feature_fraction and forced splits together can cause training failures #4601
- [x] Passing default num_threads to booster.predict not working #4607
- [x] [python] suppress the warning about categorical feature override #3379
- [ ] trees with one leaf can have strong bias in predictions, far outside observed range #4708
- [ ] Allow user to ignore `min_gain_to_split` when using forced splits by adding a hyper parameter (#4726)
- [ ] Avoiding Exception "Check failed: (best_split_info.right_count) > (0) at ..." with a regression task (#3679)
- [ ] simple repro for lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (#4739 )
## End to End Tests
- consider to leverage the related project: https://github.com/Microsoft/LightGBM-benchmark

**Comment by hzy46** [comment]
(Candidate) Bugs to be fixed:

- https://github.com/microsoft/LightGBM/issues/4657
- https://github.com/microsoft/LightGBM/issues/4239
- https://github.com/microsoft/LightGBM/issues/4601
- https://github.com/microsoft/LightGBM/issues/4607

**Comment by StrikerRUS** [comment]
@shiyu1994 @guolinke I see there are new guys with `member` and `collaborator` statuses in the LightGBM repository. This is awesome! 🚀  I think it'll good to add them into FAQ and CODEOWNERS sections (refer to #4563 or #4060 as an example).

**Comment by shiyu1994** [comment]
@StrikerRUS Yes, that would be greatly. I'll add that later today.

**Comment by shiyu1994** [comment]
Some work items for the two large PRs #3234 and #4630 are separated as feature requests. See #4779 #4780 and #4781. Contributions are welcome if you are interested @hzy46 @tongwu-msft!

**Comment by StrikerRUS** [comment]
Today is March, so closing this plan as stale. Feel free to transfer some content from this issue into a new one if needed.
