### ISSUE TITLE
[ci] [R-package] Add new linters from {lintr} 3.0

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#5303]
Now that `{lintr}` 3.0 has been released and this project is using it (#5294), I believe the project should take advantage of additional linters added in that new version.

These are documented in "New and improved features" at https://cran.r-project.org/web/packages/lintr/news/news.html.

Reading through those new linters, I believe at least the following would be useful to add  in LightGBM's CI:

* [x] `any_duplicated_linter()` (#5311)
* [x] `any_is_na_linter()` (#5306)
* [x] `class_equals_linter()` (#5307)
* [x] `duplicate_argument_linter()` (#5310)
* [x] `inner_combine_linter()` (#5311)
* [x] `literal_coercion_linter()` (#5311)
* [x] `missing_argument_linter()` (#5311)
* [x] `numeric_leading_zero_linter()` (#5311)
* [x] `outer_negation_linter()` (#5311)
* [x] `package_hooks_linter()` (#5311)
* [x] `paste_linter()` (#5320)
* [x] `sprintf_linter()` (#5311)
* [x] `regex_subset_linter()` (#5311)
* [x] `string_boundary_linter()` (#5324)
* [x] `unreachable_code_linter()` (#5311)
* [x] `vector_logic_linter()` (#5311)

### Motivation

Pushing more of the work of standardizing the project's R code into automation reduces the effort required by both reviewers and contributors in pull request reviews.

Some of these checks are not just about style...they catch efficiency or correctness issues. Doing so automatically reduces the risk of such issues being missed by contributors and reviewers.

### Approach

Pull requests for this issue are welcomed from both maintainers and outside contributors!  Please only do one or two linters per pull request, to make them easier to review and spread the work out more evenly over time.

**Comment by SaumyaBhushan** [comment]
Can you please tell me how can I do this ?

**Comment by jameslamb** [comment]
> Can you please tell me how can I do this ?

@SaumyaBhushan you can see #5306 for a good example, and the comments in https://github.com/microsoft/LightGBM/pull/5307#pullrequestreview-1011638019 for more details on how to make a successful pull request for this issue.

**Comment by SaumyaBhushan** [comment]
Thanks @jameslamb for the help.

**Comment by jameslamb** [comment]
This work is now complete. Thanks very much @CuriousCorrelation and @SaumyaBhushan ! We'd welcome additional contributions in the future if you're interested!
