### ISSUE TITLE
[ci] [python-package] Python tests leave files behind

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#6361]
## Description

The Python unit tests in this project leave some files behind when they are done running.

They should be modified to use Python-managed temporary files that are automatically removed, so that:

* successive test runs don't accidentally rely on outputs from previous runs
* files aren't left behind on developers' local systems

## Reproducible example

Build the Python package and run the Python tests.

```shell
cmake -B build -S .
cmake --build build --target _lightgbm
sh build-python.sh install --precompile
pytest tests/python_package_test
```

*(for more details on this, see #6350)*.

Look at the files created.

```shell
git status --ignored
```

As of latest `master` (https://github.com/microsoft/LightGBM/commit/b27d81ea411d04d8d071d4d4e75c19ffa15c5795), you'll see all of these created by tests:

```text
categorical.model
lgb.model
lgb.pkl
lgb_train_data.bin
model.txt
Tree4.gv.pdf
Tree4.gv
```

## Approach

Find the tests that created those files, and ensure that they stop creating them.

For example, it looks like `lgb.model` probably comes from here:

https://github.com/microsoft/LightGBM/blob/b27d81ea411d04d8d071d4d4e75c19ffa15c5795/tests/python_package_test/test_engine.py#L1373

And that that could be avoided using `pytests`'s `tmp_path` fixture, like this:

https://github.com/microsoft/LightGBM/blob/b27d81ea411d04d8d071d4d4e75c19ffa15c5795/tests/python_package_test/test_engine.py#L727

https://github.com/microsoft/LightGBM/blob/b27d81ea411d04d8d071d4d4e75c19ffa15c5795/tests/python_package_test/test_engine.py#L744

For more on how that works, see "How to use temporary directories and files in tests" ([pytest docs](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html)).

## Additional Comments

You do not need to put up a pull request fixing all of these! Contributions that fix *any* of these would be welcomed.

This list will be updated as these are fixed:

* [x] categorical.model (#6590)
* [x] data_dask.csv (#6626)
* [x] lgb.model (#6518)
* [x] lgb.pkl (#6518)
* [x] lgb_train_data.bin (#6606)
* [x] model.txt (#6590)
* [ ] preb.txt
* [x] train.binary.bin (#6606)
* [x] Tree4.gv.pdf (#6626)
* [x] Tree4.gv (#6626)

If you are interested in working on this, comment here to indicate that and to ask for help if you need it.

**Comment by Hitro147** [comment]
Hi @jameslamb ,

I'm new to open source and would like to take up this issue.

Thanks!

**Comment by jameslamb** [comment]
Sure, thanks! `@` me here if you have any questions.

**Comment by Hitro147** [comment]
Hey @jameslamb,

I have encountered a few issues while building the Python package. However, I have managed to build it successfully now. But, I am facing some errors while running the tests. I am not able to find the requirements.txt file. Can you suggest any way to install all the necessary modules?

Best,
Shrikanth

Images:
<img width="1089" alt="image" src="https://github.com/microsoft/LightGBM/assets/60385768/de136ea7-405f-4b6e-9d47-3c832ba51abb">
<img width="1090" alt="image" src="https://github.com/microsoft/LightGBM/assets/60385768/ab98cf0e-2eb3-4fa2-b37d-fb2923e42427">
<img width="1098" alt="image" src="https://github.com/microsoft/LightGBM/assets/60385768/b3eaa09b-43bb-487a-ad1c-96d5cf49565c">

**Comment by jameslamb** [comment]
Thanks for trying it out!

Please post error messages and logs as plaintext, not images, so they can be found from search engines. See these resources:

* https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors
* https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

> any way to install all the necessary modules

Follow these steps (but add `pyarrow`): https://github.com/microsoft/LightGBM/pull/6310#issuecomment-1953487883

**Comment by Hitro147** [comment]
Sorry about that! I've updated my comment. 

Thanks for the information. I'll start working on it 😄

**Comment by jameslamb** [comment]
I found another one generated by the Dask tests, added it above.

https://github.com/microsoft/LightGBM/blob/631e0a2a7bdd694a91f30378fb271d05ce438122/tests/python_package_test/test_dask.py#L1534

**Comment by Hitro147** [comment]
Hello @jameslamb,

I'm facing some issues with my current environment, but I'll need time to resolve them. However, I need to put it on hold for a while, if it's open after a while I'd like to return to it when I have more time. Feel free to assign this to someone if they are interested in this.

Thanks for giving me this opportunity! 😄

**Comment by jameslamb** [comment]
Ok sure, no problem. Comment here or on #6350 any time if you need help.

Anyone else reading this... you are welcome to contribute! A PR even just eliminating one of these left-behind files would be greatly appreciated 😊

**Comment by Arup-Chauhan** [comment]
@jameslamb, I would like to contribute to this issue, or any related good first issue (as there are multiple mentioned), here in the repository

**Comment by jameslamb** [comment]
Sure! This is a great issue to start with @Arup-Chauhan .

I recommend focusing on a single file like `categorical.model` in your first contribution, to get used to the process. You can find where it's used like this:

```shell
git grep -E 'categorical\.model'
```

Thanks for spending some time on LightGBM, we really appreciate it!

**Comment by Arup-Chauhan** [comment]
Hi @jameslamb , thanks for this, I will get started, will reach out to you once I need something

**Comment by nicklamiller** [comment]
I decided to address `lgb.model` and `lgb.pkl` in #6518.
